blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/theo/timefit-server/discussions
    about: ì¼ë°˜ì ì¸ í† ë¡ ì´ë‚˜ ì•„ì´ë””ì–´ ê³µìœ ëŠ” Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”
  - name: ğŸ“§ Email
    url: mailto:contact@example.com
    about: ê¸´ê¸‰í•˜ê±°ë‚˜ ë¯¼ê°í•œ ì‚¬í•­ì€ ì´ë©”ì¼ë¡œ ë¬¸ì˜í•´ì£¼ì„¸ìš”
